import { promises as fs } from "node:fs";
import path from "node:path";

/**
 * Serves the cropped figure PNGs, which live in data/extracted/ rather than
 * public/ because they are pipeline output, not app assets.
 *
 * Both segments are pattern-checked and the resolved path is confirmed to sit
 * inside the figures directory, so a crafted name cannot walk out of it.
 */
const YEAR_RE = /^\d{4}$/;
const NAME_RE = /^[A-Za-z0-9_-]+\.png$/;

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ year: string; name: string }> },
) {
  // Local only. Four crops still show an answer key, and these files are not
  // deployed anyway - student-facing figures come from Supabase Storage.
  //
  // Checked here rather than trusting middleware alone: the middleware matcher
  // excludes paths ending in an image extension as static assets, and these URLs
  // end in .png, so middleware never runs for this route.
  if (process.env.NODE_ENV === "production") {
    return new Response("Not found", { status: 404 });
  }

  const { year, name } = await params;

  if (!YEAR_RE.test(year) || !NAME_RE.test(name)) {
    return new Response("Not found", { status: 404 });
  }

  const dir = path.join(process.cwd(), "data", "extracted", year, "figures");
  const file = path.resolve(dir, name);
  if (path.relative(dir, file).includes("..")) {
    return new Response("Not found", { status: 404 });
  }

  try {
    const bytes = await fs.readFile(file);
    return new Response(new Uint8Array(bytes), {
      headers: {
        "Content-Type": "image/png",
        // Crops are regenerated by re-running extraction, so don't cache hard.
        "Cache-Control": "no-cache",
      },
    });
  } catch {
    return new Response("Not found", { status: 404 });
  }
}
